### Objaverse Dataset

This notebook download the objaverse dataset renderings used in Zero-1-to-3.

Author: Daniel Cho

In [ ]:
# -- download tarball of renderings --

import os

# if not os.path.exists("datasets/"):
#     os.mkdir("datasets/")
if not os.path.exists("objaverse/"):
    os.mkdir("objaverse/")

# NOTE: use curl if you don't have wget
# !curl https://tri-ml-public.s3.amazonaws.com/datasets/views_release.tar.gz -o views_release.tar.gz
!wget https://tri-ml-public.s3.amazonaws.com/datasets/views_release.tar.gz

# NOTE: put these downloaded files into the objaverse folder in the datasets directory

In [ ]:
# -- extract tarball --

import tarfile

file_path = "objaverse/views_release.tar.gz"

# # print names
# with tarfile.open(file_path, "r:gz") as tar:
#     print(tar.getnames())

with tarfile.open(file_path, "r:gz") as tar:
    extract_path = "objaverse/"
    tar.extractall(path=extract_path)
    print(f"Extracted files to: {extract_path}")

EOFError: Compressed file ended before the end-of-stream marker was reached

In each of the object folders, for every png image there's an associated .npy file. This holds the 3x4 camera matrix.

In [1]:
# -- example of information found in dataset --

import numpy as np
from scipy.linalg import rq

# load camera matrix
rt = np.load("objaverse/views_release/0a04cb6cffc14a2d8004497c23fa3dcc/000.npy")
print("RT Matrix:\n", rt)

RT Matrix:
 [[-8.29082966e-01  5.59125960e-01  2.16607177e-08  8.52643467e-08]
 [ 3.44991893e-01  5.11560559e-01  7.86947608e-01  1.19209290e-07]
 [ 4.40002769e-01  6.52444661e-01 -6.17020130e-01 -1.91990423e+00]]
